project_id = "uwvschgthdsyevfhdtey"

[functions.generate-email]
verify_jwt = false

[functions.ai-content]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.paymob-webhook]
verify_jwt = false
